import { z } from 'zod';
export const spaces = ['expiry','warranty','return','proof'] as const;
export type Space = typeof spaces[number];
export const spaceInfo = {expiry:{name:'Expiry',hint:'Food · Medicine · Daily',deadline:'Expiry date',verb:'expires'},warranty:{name:'Warranty',hint:'Laptops · Phones · Appliances',deadline:'Warranty end',verb:'warranty ends'},return:{name:'Return',hint:'Orders · Clothing',deadline:'Return deadline',verb:'return closes'},proof:{name:'Proof',hint:'Invoices · Contracts · Policies',deadline:'Valid until',verb:'expires'}};
export function validDate(s:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false; const d=new Date(s+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s;}
export const dateSchema=z.string().refine(validDate,'Enter a valid date').nullable().default(null);
export const itemInput=z.object({name:z.string().trim().min(1,'Enter a name').max(120),workspace:z.enum(spaces),brand:z.string().max(100).nullable().default(null),model:z.string().max(120).nullable().default(null),purchase_date:dateSchema,expiration_date:dateSchema,warranty_end_date:dateSchema,return_end_date:dateSchema,confidence:z.number().min(0).max(1).default(0),uncertain_fields:z.array(z.string().max(100)).max(20).default([]),evidence_quote:z.string().max(2000).default(''),notes:z.string().max(3000).default('')}).superRefine((x,c)=>{for(const field of ['warranty_end_date','return_end_date'] as const){if(x.purchase_date&&x[field]&&x[field]!<x.purchase_date)c.addIssue({code:'custom',path:[field],message:'The deadline cannot be before the purchase date'});}});
export type ItemInput=z.infer<typeof itemInput>;
export type Memory={id:string;date:string;text:string;source:'user'|'confirmed'};
export type Item=ItemInput&{id:string;status:'active'|'archived';evidence_id:string;created_at:string;memory:Memory[];demo:boolean;pilotdeck_synced?:boolean};
export type Evidence={id:string;item_id:string|null;filename:string;mime:string;key:string;size:number;created_at:string;extracted_fields:Partial<ItemInput>;demo:boolean};
export type Alert={id:string;item_id:string;evidence_id:string;type:Space;severity:'warning'|'critical';trigger_date:string;deadline:string;days_left:number;reason:string;recommendation:string;recommendation_source:'model'|'rule';memory_context:string;status:'active'|'resolved';simulated?:boolean};
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function addDays(date:string,n:number){return new Date(new Date(date+'T00:00:00Z').getTime()+n*86400000).toISOString().slice(0,10);}
export function deadline(item:ItemInput){return item.workspace==='warranty'?item.warranty_end_date:item.workspace==='return'?item.return_end_date:item.expiration_date;}
export function daysLeft(item:ItemInput,date=today()){const d=deadline(item);return d?Math.round((new Date(d+'T00:00:00Z').getTime()-new Date(date+'T00:00:00Z').getTime())/86400000):null;}
export function evaluateRisk(item:Item,date=today()):Alert|null{const end=deadline(item),days=daysLeft(item,date);if(item.status!=='active'||!end||days===null)return null;const critical=item.workspace==='warranty'?7:1,warning=(item.workspace==='warranty'||item.workspace==='proof')?30:3;if(days>warning)return null;const label=spaceInfo[item.workspace];const span=(n:number)=>`${n} day${n===1?'':'s'}`;const reason=days<0?`${label.deadline} passed ${span(-days)} ago (${end}).`:days===0?`${label.deadline} is today (${end}).`:`${span(days)} until ${label.deadline.toLowerCase()} (${end}).`;const issue=item.memory.filter(m=>m.source==='user').map(m=>m.text).join('; ');const recommendation=days<0?'Check the original evidence, then ask the seller what can still be done.':item.workspace==='warranty'?(issue?`Report "${issue.slice(0,90)}" to support before the warranty ends.`:'Check the device for faults while the warranty still covers it.'):item.workspace==='expiry'?'Check the date on the package and plan to use it.':item.workspace==='return'?'Decide whether to keep it, and start the return before the deadline.':'Review the terms and check whether it needs renewing.';return{id:`alert-${item.id}-${end}`,item_id:item.id,evidence_id:item.evidence_id,type:item.workspace,severity:days<=critical?'critical':'warning',trigger_date:date,deadline:end,days_left:days,reason,recommendation,recommendation_source:'rule',memory_context:issue,status:'active'};}
