import { z } from 'zod';
export const spaces = ['expiry','warranty','return','proof'] as const;
export type Space = typeof spaces[number];
export const spaceInfo = {expiry:{name:'Expiry',label:'到期',description:'食品 · 药品 · 日用品',deadline:'到期日期',verb:'到期'},warranty:{name:'Warranty',label:'保修',description:'数码 · 家电 · 保修',deadline:'保修截止',verb:'过保'},return:{name:'Return',label:'售后',description:'订单 · 退换 · 售后',deadline:'退货截止',verb:'结束退货'},proof:{name:'Proof',label:'凭证',description:'发票 · 合同 · 凭证',deadline:'有效期截止',verb:'到期'}};
export function validDate(s:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false; const d=new Date(s+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s;}
export const dateSchema=z.string().refine(validDate,'请填写有效日期').nullable().default(null);
export const itemInput=z.object({name:z.string().trim().min(1,'请填写物品名称').max(120),workspace:z.enum(spaces),brand:z.string().max(100).nullable().default(null),model:z.string().max(120).nullable().default(null),purchase_date:dateSchema,expiration_date:dateSchema,warranty_end_date:dateSchema,return_end_date:dateSchema,confidence:z.number().min(0).max(1).default(0),uncertain_fields:z.array(z.string().max(100)).max(20).default([]),evidence_quote:z.string().max(2000).default(''),notes:z.string().max(3000).default('')}).superRefine((x,c)=>{for(const field of ['warranty_end_date','return_end_date'] as const){if(x.purchase_date&&x[field]&&x[field]!<x.purchase_date)c.addIssue({code:'custom',path:[field],message:'截止日期不能早于购买日期'});}});
export type ItemInput=z.infer<typeof itemInput>;
export type Memory={id:string;date:string;text:string;source:'user'|'confirmed'};
export type Item=ItemInput&{id:string;status:'active'|'archived';evidence_id:string;created_at:string;memory:Memory[];demo:boolean;pilotdeck_synced?:boolean};
export type Evidence={id:string;item_id:string|null;filename:string;mime:string;key:string;size:number;created_at:string;extracted_fields:Partial<ItemInput>;demo:boolean};
export type Alert={id:string;item_id:string;evidence_id:string;type:Space;severity:'warning'|'critical';trigger_date:string;deadline:string;days_left:number;reason:string;recommendation:string;recommendation_source:'model'|'rule';memory_context:string;status:'active'|'resolved';simulated?:boolean};
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function addDays(date:string,n:number){return new Date(new Date(date+'T00:00:00Z').getTime()+n*86400000).toISOString().slice(0,10);}
export function deadline(item:ItemInput){return item.workspace==='warranty'?item.warranty_end_date:item.workspace==='return'?item.return_end_date:item.expiration_date;}
export function daysLeft(item:ItemInput,date=today()){const d=deadline(item);return d?Math.round((new Date(d+'T00:00:00Z').getTime()-new Date(date+'T00:00:00Z').getTime())/86400000):null;}
export function evaluateRisk(item:Item,date=today()):Alert|null{const end=deadline(item),days=daysLeft(item,date);if(item.status!=='active'||!end||days===null)return null;const critical=item.workspace==='warranty'?7:1,warning=(item.workspace==='warranty'||item.workspace==='proof')?30:3;if(days>warning)return null;const label=spaceInfo[item.workspace];const reason=days<0?`${label.deadline}已过 ${-days} 天（${end}）。`:days===0?`今天是${label.deadline}（${end}）。`:`距离${label.deadline}还有 ${days} 天（${end}）。`;const issue=item.memory.filter(m=>m.source==='user').map(m=>m.text).join('；');const recommendation=days<0?'先核对原始凭证，再联系相关商家确认后续处理方式。':item.workspace==='warranty'?(issue?`针对你记录的“${issue.slice(0,90)}”，请在保修结束前联系售后检测。`:'在保修结束前检查设备是否有需要处理的故障。'):item.workspace==='expiry'?'核对包装上的日期与保存要求，安排使用。':item.workspace==='return'?'确认是否保留这件物品，需要退货请在截止前申请。':'核对原件条款，确认是否需要续期。';return{id:`alert-${item.id}-${end}`,item_id:item.id,evidence_id:item.evidence_id,type:item.workspace,severity:days<=critical?'critical':'warning',trigger_date:date,deadline:end,days_left:days,reason,recommendation,recommendation_source:'rule',memory_context:issue,status:'active'};}
