"use client";
import {createContext,createElement,useContext,useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {House,LayoutGrid,Plus,Bell,User,ChevronLeft,ChevronRight,Pencil,Camera,Images,X,Check,Sparkles,ExternalLink,LoaderCircle,Milk,ShieldCheck,Package,FileText,Laptop,Smartphone,Tablet,Headphones,Watch,Tv,Refrigerator,Pill,Footprints,Shirt} from 'lucide-react';
import {Drawer as V} from 'vaul';
import {Toaster,toast} from 'sonner';
import {spaceInfo,spaces,deadline,daysLeft,today,addDays,type Item,type ItemInput,type Space,type Alert} from '@/lib/later/domain';

type View='home'|'items'|'alerts'|'me'|'item'|'add';
type Tab='home'|'items'|'alerts'|'me';
type Filter=Space|'all'|'archived';
type Snapshot={items:Item[];alerts:Alert[];today:string;pilotdeck:any;evidence:Record<string,string>};
type Glyph=typeof Milk;
type EndKey='expiration_date'|'warranty_end_date'|'return_end_date';

const tabs:Tab[]=['home','items','alerts','me'];
const paths:Record<Exclude<View,'item'>,string>={home:'/',items:'/spaces',alerts:'/alerts',me:'/me',add:'/add'};
const empty:ItemInput={name:'',workspace:'proof',brand:null,model:null,purchase_date:null,expiration_date:null,warranty_end_date:null,return_end_date:null,confidence:0,uncertain_fields:[],evidence_quote:'',notes:''};
const spaceGlyphs:Record<Space,Glyph>={expiry:Milk,warranty:ShieldCheck,return:Package,proof:FileText};
// Recognisable objects get their own glyph; everything else falls back to its space.
const nameGlyphs:[RegExp,Glyph][]=[[/耳机|airpods/i,Headphones],[/macbook|笔记本|电脑/i,Laptop],[/iphone|手机/i,Smartphone],[/ipad|平板/i,Tablet],[/手表|watch/i,Watch],[/电视|显示器/i,Tv],[/冰箱/i,Refrigerator],[/相机/i,Camera],[/奶/i,Milk],[/药|胶囊/i,Pill],[/鞋|nike|adidas/i,Footprints],[/衣|裤|裙|衫|外套/i,Shirt]];
const endLabel:Record<Space,string>={expiry:'到期日',warranty:'保修至',return:'退货截止',proof:'有效期至'};
const endKey=(s:Space):EndKey=>s==='warranty'?'warranty_end_date':s==='return'?'return_end_date':'expiration_date';
// Sheets portal into the phone screen so they stay inside the device frame on desktop.
const PortalHost=createContext<HTMLElement|null>(null);

async function request(body?:unknown){const res=await fetch('/api/later',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data:any=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'网络不稳定，请重试');return data;}
function locate():{view:View;id:string}{const p=location.pathname;if(p.startsWith('/item/'))return{view:'item',id:decodeURIComponent(p.split('/')[2]||'')};const view:View=p==='/spaces'?'items':p==='/alerts'||new URLSearchParams(location.search).get('view')==='alerts'?'alerts':p==='/me'?'me':p==='/add'?'add':'home';return{view,id:''};}
const glyphFor=(item:Pick<Item,'name'|'workspace'>)=>nameGlyphs.find(([re])=>re.test(item.name))?.[1]??spaceGlyphs[item.workspace];
const dayNum=(s:string)=>Date.parse(s+'T00:00:00Z')/864e5;
function dateText(s:string|null|undefined,now:string){if(!s)return '';const [y,m,d]=s.split('-').map(Number);return `${String(y)===now.slice(0,4)?'':y+'年'}${m}月${d}日`;}
function weekday(now:string){const d=new Date(now+'T12:00:00');return `${d.getMonth()+1}月${d.getDate()}日 周${'日一二三四五六'[d.getDay()]}`;}
function statusText(item:Item,now:string){if(item.status==='archived')return '已归档';const d=daysLeft(item,now),s=item.workspace;if(d===null)return s==='proof'?'已存档':'未设期限';if(s==='return')return d<0?'退货已截止':d===0?'今天截止退货':`还有 ${d} 天可退`;const verb=s==='warranty'?'过保':'到期';return d<0?`已${verb} ${-d} 天`:d===0?`今天${verb}`:`还有 ${d} 天${verb}`;}
function countdown(item:Item,now:string){const d=daysLeft(item,now),s=item.workspace;if(d===null)return{num:'',unit:s==='proof'?'已存档':'未设期限'};const verb=s==='warranty'?'过保':s==='return'?'截止退货':'到期';if(d===0)return{num:'今天',unit:verb};return d<0?{num:String(-d),unit:`天前已${verb}`}:{num:String(d),unit:s==='return'?'天内可退':`天后${verb}`};}
function elapsed(item:Item,now:string){const end=deadline(item),start=item.purchase_date;if(!end||!start||end<=start)return null;return Math.min(1,Math.max(0,(dayNum(now)-dayNum(start))/(dayNum(end)-dayNum(start))));}

function Pig({className=''}:{className?:string}){return <svg className={'pig '+className} viewBox="0 0 64 64" fill="none" stroke="currentColor" strokeWidth={2.6} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M19.5 19.4 15 8.5l12 7.1M44.5 19.4 49 8.5l-12 7.1"/><circle cx="32" cy="35" r="20"/><ellipse cx="32" cy="41" rx="8.5" ry="6"/><g fill="currentColor" stroke="none"><circle cx="29" cy="41" r="1.4"/><circle cx="35" cy="41" r="1.4"/><circle cx="24.5" cy="30" r="1.9"/><circle cx="39.5" cy="30" r="1.9"/></g></svg>;}
function Thumb({item,mime,large=false}:{item:Item;mime?:string;large?:boolean}){const [broken,setBroken]=useState(false);return <span className={'thumb'+(large?' lg':'')} data-space={item.workspace}>{mime?.startsWith('image/')&&!broken?<img src={`/api/evidence/${item.evidence_id}`} alt="" loading="lazy" onError={()=>setBroken(true)}/>:createElement(glyphFor(item),{strokeWidth:1.6})}</span>;}
function ItemRow({item,now,mime,urgent=false,note,index,onOpen}:{item:Item;now:string;mime?:string;urgent?:boolean;note?:string;index:number;onOpen:()=>void}){return <button className="item-row" style={{'--i':index} as CSSProperties} onClick={onOpen}><Thumb item={item} mime={mime}/><span className="row-main"><strong>{item.name}</strong><span className={'row-status'+(urgent?' urgent':'')}>{statusText(item,now)}</span>{note&&<span className="row-note">{note}</span>}</span><ChevronRight className="chev" size={18}/></button>;}
function Sheet({open,onClose,title,action,className='',children}:{open:boolean;onClose:()=>void;title:string;action?:ReactNode;className?:string;children:ReactNode}){const host=useContext(PortalHost);return <V.Root open={open} onOpenChange={o=>{if(!o)onClose();}}><V.Portal container={host??undefined}><V.Overlay className="sheet-overlay"/><V.Content className={'sheet '+className}><div className="sheet-handle" aria-hidden="true"/><div className="sheet-head"><V.Title className="sheet-title">{title}</V.Title>{action}</div><V.Description className="sr-only">{title}</V.Description><div className="sheet-body">{children}</div></V.Content></V.Portal></V.Root>;}
function DateRow({label,value,onChange,flag=false,now}:{label:string;value:string|null;onChange:(v:string|null)=>void;flag?:boolean;now:string}){return <div className="row date-row"><span>{label}{flag&&<i className="flag" title="请核对"/>}</span><span className={'val'+(value?'':' placeholder')}>{value?dateText(value,now):'未填写'}</span>{value&&<button type="button" className="clear" aria-label={`清除${label}`} onClick={()=>onChange(null)}><X size={13}/></button>}<input type="date" value={value||''} aria-label={label} onChange={e=>onChange(e.target.value||null)} onClick={e=>{try{e.currentTarget.showPicker();}catch{/* native picker opens on tap */}}}/></div>;}
function ItemForm({value,onChange,now}:{value:ItemInput;onChange:(x:ItemInput)=>void;now:string}){const key=endKey(value.workspace),unsure=(f:string)=>value.uncertain_fields.includes(f);
 // Switching space carries a recognised deadline over instead of silently dropping it.
 function pick(s:Space){const from=endKey(value.workspace),to=endKey(s);onChange({...value,workspace:s,...(from!==to&&value[from]&&!value[to]?{[to]:value[from],[from]:null}:{})});}
 return <div className="form"><input className="name-input" value={value.name} maxLength={120} autoComplete="off" placeholder="物品名称" aria-label="物品名称" onChange={e=>onChange({...value,name:e.target.value})}/><div className="seg" role="radiogroup" aria-label="分类">{spaces.map(s=><button type="button" role="radio" aria-checked={value.workspace===s} key={s} className={value.workspace===s?'on':''} onClick={()=>pick(s)}>{spaceInfo[s].name}</button>)}</div><div className="group"><DateRow label={value.workspace==='proof'?'签订日期':'购买日期'} value={value.purchase_date} flag={unsure('purchase_date')} now={now} onChange={v=>onChange({...value,purchase_date:v})}/><DateRow label={endLabel[value.workspace]} value={value[key]} flag={unsure(key)} now={now} onChange={v=>onChange({...value,[key]:v})}/><label className="row note-row"><span>备注</span><textarea rows={Math.min(4,Math.max(1,Math.ceil(value.notes.length/16)))} value={value.notes} maxLength={3000} placeholder="可选" onChange={e=>onChange({...value,notes:e.target.value})}/></label></div>{!value[key]&&value.workspace!=='proof'&&<p className="hint">没有找到期限，可以稍后补充</p>}</div>;}

export default function LaterApp({initialView='home',initialId=''}:{initialView?:View;initialId?:string}){
const [view,setView]=useState<View>(initialView),[selectedId,setSelectedId]=useState(initialId),[lastTab,setLastTab]=useState<Tab>(tabs.includes(initialView as Tab)?initialView as Tab:'home'),[filter,setFilter]=useState<Filter>('all');
const [data,setData]=useState<Snapshot>({items:[],alerts:[],today:today(),pilotdeck:null,evidence:{}}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('');
const [pickOpen,setPickOpen]=useState(false),[uploadFile,setUploadFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[uploading,setUploading]=useState(false),[uploadStep,setUploadStep]=useState(''),[draft,setDraft]=useState<ItemInput|null>(null),[draftEvidence,setDraftEvidence]=useState(''),[uploadWarning,setUploadWarning]=useState('');
const [viewer,setViewer]=useState<{id:string;mime:string}|null>(null),[edit,setEdit]=useState<ItemInput|null>(null),[noteOpen,setNoteOpen]=useState(false),[note,setNote]=useState(''),[simOpen,setSimOpen]=useState(false),[simDate,setSimDate]=useState(''),[simResult,setSimResult]=useState<Alert[]|null>(null),[showResolved,setShowResolved]=useState(false);
const [host,setHost]=useState<HTMLElement|null>(null);
const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),scrollRef=useRef<HTMLDivElement>(null),previewRef=useRef('');
function setUpload(file:File|null){if(previewRef.current)URL.revokeObjectURL(previewRef.current);previewRef.current=file?URL.createObjectURL(file):'';setUploadFile(file);setPreview(previewRef.current);}
async function reload(){try{const result=await request();setData({evidence:{},...result});setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{void reload();const interval=setInterval(()=>void reload(),60000);const sync=()=>{const at=locate();setView(at.view);if(at.id)setSelectedId(at.id);if(tabs.includes(at.view as Tab))setLastTab(at.view as Tab);};sync();window.addEventListener('popstate',sync);return()=>{clearInterval(interval);window.removeEventListener('popstate',sync);};},[]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'later_list_items',title:'查看 Later 物品',description:'Read saved belongings and active alerts. Does not change data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No arguments accepted');const result=await request();setData({evidence:{},...result});return{items:result.items.map((i:Item)=>({id:i.id,name:i.name,workspace:i.workspace,status:i.status,deadline:deadline(i)})),alerts:result.alerts.filter((a:Alert)=>a.status==='active')};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);

function go(next:View,id?:string){setView(next);if(id)setSelectedId(id);if(tabs.includes(next as Tab))setLastTab(next as Tab);history.pushState(null,'',next==='item'?`/item/${id}`:paths[next]);scrollRef.current?.scrollTo(0,0);window.scrollTo(0,0);}
async function action(label:string,body:unknown){setBusy(label);try{const r=await request(body);await reload();return r;}catch(e){toast.error((e as Error).message);return null;}finally{setBusy('');}}
async function inspect(date?:string,quiet=false){const r=await action('scan',{action:'scan',...(date?{date}:{})});if(r&&date)setSimResult(r.alerts);else if(r&&!quiet)toast.success(`已检查 ${r.checked} 件物品`);}
async function seed(){const r=await action('seed',{action:'seed'});if(r)toast.success(r.already?'示例已经在了':'已添加示例物品');}
async function syncMemory(){const r=await action('sync',{action:'sync'});if(r)toast(r.synced?`已同步 ${r.synced} 件物品`:'记忆服务未连接，资料已安全保存');}
function resetAdd(){setDraft(null);setDraftEvidence('');setUpload(null);setUploadWarning('');}
function choose(input:HTMLInputElement|null){input?.click();setPickOpen(false);}
async function upload(file:File){if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)){toast.error('请选择图片或 PDF');return;}if(file.size>8*1024*1024){toast.error('文件需小于 8 MB');return;}resetAdd();setUpload(file);setUploading(true);setUploadStep('稍等片刻');go('add');try{const form=new FormData();form.set('file',file);if(file.type==='application/pdf'){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer(),isEvalSupported:false}).promise;if(pdf.numPages>6){await pdf.destroy();throw new Error('PDF 最多 6 页，请拆分后再试');}for(let p=1;p<=pdf.numPages;p++){setUploadStep(`第 ${p} / ${pdf.numPages} 页`);const page=await pdf.getPage(p),vp=page.getViewport({scale:1});const viewport=page.getViewport({scale:Math.min(1.8,1500/Math.max(vp.width,vp.height))});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvas,canvasContext:canvas.getContext('2d')!,viewport}).promise;const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('文件读取失败')),'image/jpeg',.85));form.append('pages',blob,`page-${p}.jpg`);canvas.width=0;canvas.height=0;}await pdf.destroy();setUploadStep('稍等片刻');}const r=await fetch('/api/upload',{method:'POST',body:form});const result:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||'上传失败，请重试');setDraft({...empty,...result.recognition});setDraftEvidence(result.evidence_id);setUploadWarning(result.warning?'没能识别出来，请手动填写':'');}catch(e){setUploadWarning((e as Error).message);toast.error((e as Error).message);}finally{setUploading(false);if(fileRef.current)fileRef.current.value='';if(cameraRef.current)cameraRef.current.value='';}}
async function confirm(){if(!draft)return;const r=await action('confirm',{action:'confirm',item:draft,evidence_id:draftEvidence});if(r?.item){toast.success('已保存');resetAdd();go('item',r.item.id);void inspect(undefined,true);}}

const now=data.today,pd=data.pilotdeck,isTab=tabs.includes(view as Tab);
const activeItems=data.items.filter(i=>i.status==='active');
const activeAlerts=data.alerts.filter(a=>a.status==='active'&&activeItems.some(i=>i.id===a.item_id));
const alertFor=(id:string)=>activeAlerts.find(a=>a.item_id===id);
// Alerts first (soonest first), then upcoming deadlines, then items without one.
const rank=(i:Item)=>{const d=daysLeft(i,now);return (alertFor(i.id)?0:d===null?2e6:1e6)+(d??0);};
const sorted=[...activeItems].sort((a,b)=>rank(a)-rank(b));
const alertItems=sorted.filter(i=>alertFor(i.id));
const resolved=data.alerts.filter(a=>a.status==='resolved'&&data.items.some(i=>i.id===a.item_id));
const selected=data.items.find(i=>i.id===selectedId),selectedAlert=selected?alertFor(selected.id):undefined;
const listed=filter==='archived'?data.items.filter(i=>i.status==='archived'):sorted.filter(i=>filter==='all'||i.workspace===filter);
const row=(item:Item,index:number,note?:string)=><ItemRow key={item.id} index={index} item={item} now={now} mime={data.evidence[item.evidence_id]} urgent={!!alertFor(item.id)} note={note} onOpen={()=>go('item',item.id)}/>;
const banner=error?<button className="banner" onClick={()=>void reload()}>网络不稳定，轻触重试</button>:null;
const skeleton=<div className="list">{[0,1,2].map(i=><div className="skeleton" key={i}/>)}</div>;
const tab=(v:Tab,Icon:Glyph,label:string,badge=0)=><button key={v} className={'tab'+(view===v?' on':'')} aria-current={view===v?'page':undefined} onClick={()=>go(v)}><Icon strokeWidth={view===v?2.2:1.8}/>{label}{badge>0&&<span className="badge">{badge}</span>}</button>;

return <PortalHost.Provider value={host}><div className="stage">
<div className="stage-brand" aria-hidden="true"><p className="wordmark">Later</p><h2>未来回响</h2><p>让今天沉下去的信息，<br/>在未来需要时重新浮现。</p><span className="stage-sign"><Pig/>一只乐于助人的猪</span></div>
<div className="device"><div className="glass" ref={setHost}><div className={'app'+(isTab?'':' bare')} ref={scrollRef}><Toaster position="top-center" toastOptions={{className:'toast'}}/>
<main>
{view==='home'&&<section className="screen" key="home"><header className="home-hero"><div><h1 className="wordmark">Later</h1><p className="home-sub">{loading?'正在加载':alertItems.length?<><b>{alertItems.length}</b> 件事需要留意</>:activeItems.length?'一切安好':'替你记着重要的日子'}</p></div><span className="today">{weekday(now)}</span></header>{banner}
{loading?skeleton:sorted.length?<><div className="list">{sorted.slice(0,6).map((item,i)=>row(item,i,i===0?alertFor(item.id)?.recommendation:undefined))}</div>{sorted.length>6&&<button className="more" onClick={()=>go('items')}>全部 {sorted.length} 件<ChevronRight size={16}/></button>}</>
:<div className="empty"><Pig/><h2>从一张凭证开始</h2><p>小票、发票、包装，拍下来就好</p><button className="btn" onClick={()=>setPickOpen(true)}><Plus size={18}/>添加</button>{!data.items.length&&<button className="link" disabled={!!busy} onClick={()=>void seed()}>先看看示例</button>}</div>}</section>}

{view==='items'&&<section className="screen" key="items"><h1 className="page-title">物品</h1>{banner}<div className="chips">{(['all',...spaces,'archived'] as Filter[]).map(f=><button key={f} className={'chip'+(filter===f?' on':'')} onClick={()=>setFilter(f)}>{f==='all'?'全部':f==='archived'?'归档':spaceInfo[f].name}</button>)}</div>
{loading?skeleton:listed.length?<div className="list" key={filter}>{listed.map((item,i)=>row(item,i))}</div>:<div className="empty small"><Pig/><p>{filter==='archived'?'没有归档的物品':'这里还空着'}</p></div>}</section>}

{view==='alerts'&&<section className="screen" key="alerts"><h1 className="page-title">提醒</h1>{banner}
{loading?skeleton:alertItems.length?<div className="list">{alertItems.map((item,i)=>row(item,i,alertFor(item.id)?.recommendation))}</div>:<div className="empty"><Pig/><h2>暂无提醒</h2><p>临近期限时，会在这里告诉你</p></div>}
{resolved.length>0&&<><button className={'toggle'+(showResolved?' open':'')} onClick={()=>setShowResolved(!showResolved)}>已处理 {resolved.length}<ChevronRight size={16}/></button>{showResolved&&<div className="group">{resolved.slice(0,20).map(a=>{const item=data.items.find(i=>i.id===a.item_id)!;return <button className="row" key={a.id} onClick={()=>go('item',item.id)}><Check size={16} className="ok"/><span className="ellipsis">{item.name}</span><span className="val">{dateText(a.deadline,now)}</span></button>;})}</div>}</>}</section>}

{view==='me'&&<section className="screen" key="me"><div className="me-head"><Pig/><p className="wordmark">Later</p><p>一只乐于助人的猪</p></div>
<div className="stats"><div><strong>{activeItems.length}</strong><span>物品</span></div><div><strong>{activeAlerts.length}</strong><span>提醒</span></div><div><strong>{resolved.length}</strong><span>已处理</span></div></div>
<div className="group"><div className="row"><span>每日检查</span><span className="val"><i className={'dot'+(pd?.connected?' on':'')}/>{pd?.connected?'每天 9:00':'未开启'}</span></div><button className="row" disabled={!!busy} onClick={()=>void inspect()}><span>立即检查</span>{busy==='scan'?<LoaderCircle className="spin chev" size={18}/>:<ChevronRight className="chev" size={18}/>}</button><button className="row" onClick={()=>{setSimResult(null);setSimDate(addDays(now,7));setSimOpen(true);}}><span>预览未来</span><ChevronRight className="chev" size={18}/></button><button className="row" disabled={!!busy} onClick={()=>void syncMemory()}><span>记忆同步</span><span className="val">{pd?.connected?'已连接':'离线'}</span><ChevronRight className="chev" size={18}/></button></div>
{!loading&&!data.items.some(i=>i.demo)&&<div className="group"><button className="row" disabled={!!busy} onClick={()=>void seed()}><span>添加示例物品</span><ChevronRight className="chev" size={18}/></button></div>}
<p className="motto">今天存下 · 明天安心</p></section>}

{view==='item'&&<section className="screen" key={'item-'+selectedId}><div className="topnav"><button className="icon-btn" aria-label="返回" onClick={()=>go(lastTab)}><ChevronLeft size={26}/></button><span/>{selected&&<button className="icon-btn" aria-label="编辑" onClick={()=>setEdit({...selected})}><Pencil size={19}/></button>}</div>
{selected?(()=>{const c=countdown(selected,now),end=deadline(selected),pct=elapsed(selected,now);return <>
<div className="hero"><Thumb item={selected} mime={data.evidence[selected.evidence_id]} large/><h1>{selected.name}</h1><span className="pill" data-space={selected.workspace}>{spaceInfo[selected.workspace].name}{selected.demo?' · 示例':''}{selected.status==='archived'?' · 已归档':''}</span></div>
<div className={'count'+(selectedAlert?' urgent':'')}><div className="big">{c.num?<><strong>{c.num}</strong><span>{c.unit}</span></>:<span className="plain">{c.unit}</span>}</div>{pct!==null?<div className="span"><div className="bar"><i style={{width:`${Math.max(pct*100,3)}%`}}/></div><div className="span-dates"><span>{dateText(selected.purchase_date,now)}</span><span>{dateText(end,now)}</span></div></div>:end&&<small>{dateText(end,now)}</small>}</div>
{selectedAlert&&<div className="advice"><Pig className="advice-pig"/><span className="advice-label"><Sparkles size={14}/>建议</span><p>{selectedAlert.recommendation}</p><button disabled={!!busy} onClick={async()=>{if(await action('resolve',{action:'resolve',id:selectedAlert.id}))toast.success('已处理');}}><Check size={16}/>已处理</button></div>}
<div className="group"><button className="row" onClick={()=>setViewer({id:selected.evidence_id,mime:data.evidence[selected.evidence_id]||''})}><span>凭证</span><span className="val">查看</span><ChevronRight className="chev" size={18}/></button>{selected.purchase_date&&pct===null&&<div className="row"><span>{selected.workspace==='proof'?'签订日期':'购买日期'}</span><span className="val">{dateText(selected.purchase_date,now)}</span></div>}{selected.notes&&<div className="row multi"><span>备注</span><span className="val">{selected.notes}</span></div>}</div>
<div className="section-head"><span>记录</span><button onClick={()=>setNoteOpen(true)}><Plus size={16}/>记一笔</button></div>
<div className="timeline">{[...selected.memory].sort((a,b)=>b.date.localeCompare(a.date)).map(m=><div className={'tl'+(m.source==='user'?' mine':'')} key={m.id}><time>{dateText(m.date,now)}</time><p>{m.text.replace(/。$/,'')}</p></div>)}</div>
<button className="archive" disabled={!!busy} onClick={async()=>{const r=await action('archive',{action:'archive',id:selected.id});if(r)toast.success(selected.status==='active'?'已归档':'已恢复');}}>{selected.status==='active'?'归档':'恢复'}</button></>;})()
:<div className="empty small"><Pig/><p>{loading?'正在加载':'没有找到这件物品'}</p></div>}</section>}

{view==='add'&&<section className="screen" key="add"><div className="topnav"><button className="icon-btn" aria-label="关闭" onClick={()=>{resetAdd();go(lastTab);}}><X size={22}/></button><span className="topnav-title">{draft&&!uploading?'核对信息':''}</span><span/></div>
{uploading?<div className="scan"><div className="scan-frame">{preview&&uploadFile?.type.startsWith('image/')?<img src={preview} alt=""/>:<FileText size={48} strokeWidth={1.2}/>}</div><h2>正在识别</h2><p>{uploadStep}</p></div>
:draft?<>{uploadWarning&&<p className="warn">{uploadWarning}</p>}<button className="preview" aria-label="查看凭证" onClick={()=>setViewer({id:draftEvidence,mime:uploadFile?.type||''})}>{preview&&uploadFile?.type.startsWith('image/')?<img src={preview} alt=""/>:<span className="preview-file"><FileText size={30} strokeWidth={1.4}/>{uploadFile?.name}</span>}</button><ItemForm value={draft} onChange={setDraft} now={now}/><div className="bottom-bar"><button className="btn block" disabled={!!busy||!draft.name.trim()} onClick={()=>void confirm()}>{busy==='confirm'&&<LoaderCircle className="spin" size={18}/>}保存</button></div></>
:<div className="start"><div className="start-art"><Camera size={44} strokeWidth={1.3}/></div><h2>拍下凭证</h2><p>识别物品和日期，你确认后保存</p>{uploadWarning&&<p className="warn">{uploadWarning}</p>}<button className="btn block" onClick={()=>cameraRef.current?.click()}><Camera size={19}/>拍照</button><button className="btn block ghost" onClick={()=>fileRef.current?.click()}><Images size={19}/>选择文件</button></div>}</section>}
</main>

{isTab&&<nav className="tabbar" aria-label="主导航">{tab('home',House,'首页')}{tab('items',LayoutGrid,'物品')}<button className="fab" aria-label="添加" onClick={()=>setPickOpen(true)}><Plus strokeWidth={2.2}/></button>{tab('alerts',Bell,'提醒',activeAlerts.length)}{tab('me',User,'我的')}</nav>}
<input className="sr-only" ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,application/pdf" aria-label="选择凭证文件" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><input className="sr-only" ref={cameraRef} type="file" accept="image/*" capture="environment" aria-label="拍摄凭证" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/>
</div></div></div>

<Sheet open={pickOpen} onClose={()=>setPickOpen(false)} title="添加"><div className="pick"><button onClick={()=>choose(cameraRef.current)}><span className="pick-ic"><Camera size={24}/></span>拍照</button><button onClick={()=>choose(fileRef.current)}><span className="pick-ic"><Images size={24}/></span>选择文件</button></div></Sheet>
<Sheet open={!!viewer} onClose={()=>setViewer(null)} title="凭证" className="viewer" action={viewer&&<a className="icon-btn" href={`/api/evidence/${viewer.id}`} target="_blank" rel="noreferrer" aria-label="新窗口打开"><ExternalLink size={18}/></a>}>{viewer&&(viewer.mime.startsWith('image/')?<img className="viewer-media" src={`/api/evidence/${viewer.id}`} alt="凭证原件"/>:<iframe className="viewer-media" title="凭证原件" src={`/api/evidence/${viewer.id}`}/>)}</Sheet>
<Sheet open={!!edit} onClose={()=>setEdit(null)} title="编辑">{edit&&<><ItemForm value={edit} onChange={setEdit} now={now}/><button className="btn block mt" disabled={!!busy||!edit.name.trim()} onClick={async()=>{if(!selected)return;const r=await action('update',{action:'update',id:selected.id,item:edit});if(r){setEdit(null);toast.success('已更新');void inspect(undefined,true);}}}>保存</button></>}</Sheet>
<Sheet open={noteOpen} onClose={()=>setNoteOpen(false)} title="记一笔"><textarea className="note-input" rows={4} maxLength={1500} value={note} onChange={e=>setNote(e.target.value)} placeholder="比如：充电时偶尔断连" aria-label="记录内容"/><button className="btn block mt" disabled={!!busy||!note.trim()} onClick={async()=>{if(!selected)return;const r=await action('issue',{action:'issue',id:selected.id,text:note});if(r){setNote('');setNoteOpen(false);toast.success('记下了');void inspect(undefined,true);}}}>保存</button></Sheet>
<Sheet open={simOpen} onClose={()=>setSimOpen(false)} title="预览未来"><div className="group"><DateRow label="假如今天是" value={simDate} now={now} onChange={v=>{setSimDate(v||'');setSimResult(null);}}/></div><button className="btn block mt" disabled={!!busy||!simDate} onClick={()=>void inspect(simDate)}>{busy==='scan'&&<LoaderCircle className="spin" size={18}/>}预览</button>{simResult&&(simResult.length?<div className="group">{simResult.map(a=><div className="row" key={a.id}><span className="ellipsis">{data.items.find(i=>i.id===a.item_id)?.name}</span><span className="val urgent">{a.days_left<0?`已过 ${-a.days_left} 天`:a.days_left===0?'当天截止':`剩 ${a.days_left} 天`}</span></div>)}</div>:<p className="quiet">那天没有提醒</p>)}</Sheet>
</div></PortalHost.Provider>;
}
