"use client";
import {createContext,createElement,useContext,useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {CalendarDays,CalendarClock,Search,Plus,ChevronLeft,ChevronRight,Pencil,Camera,Images,X,Check,Sparkles,ExternalLink,LoaderCircle,Milk,ShieldCheck,Package,FileText,Laptop,Smartphone,Tablet,Headphones,Watch,Tv,Refrigerator,Pill,Footprints,Shirt,Mail,LockKeyhole,UserRound,LogOut,ArrowRight,MessageSquareText} from 'lucide-react';
import {Drawer as V} from 'vaul';
import {Toaster,toast} from 'sonner';
import {spaceInfo,spaces,deadline,daysLeft,today,addDays,type Item,type ItemInput,type Space,type Alert} from '@/lib/later/domain';

type View='today'|'search'|'storage'|'add'|'item';
type Tab='today'|'search';
type Snapshot={items:Item[];alerts:Alert[];today:string;pilotdeck:any;evidence:Record<string,string>};
type Profile={name:string;email:string;avatar?:string};
type Account=Profile&{passwordHash:string};
type Glyph=typeof Milk;
type EndKey='expiration_date'|'warranty_end_date'|'return_end_date';

const PROFILE_KEY='later.profile';
const ACCOUNT_KEY='later.account';
const SESSION_KEY='later.session';
const SAMPLES_KEY='later.samples.visible';
const paths:Record<Exclude<View,'item'>,string>={today:'/',search:'/search',storage:'/storage',add:'/add'};
const empty:ItemInput={name:'',workspace:'proof',brand:null,model:null,purchase_date:null,expiration_date:null,warranty_end_date:null,return_end_date:null,confidence:0,uncertain_fields:[],evidence_quote:'',notes:''};
const spaceGlyphs:Record<Space,Glyph>={expiry:Milk,warranty:ShieldCheck,return:Package,proof:FileText};
// Recognisable objects get their own glyph; everything else falls back to its space.
const nameGlyphs:[RegExp,Glyph][]=[[/headphone|airpods|earbud/i,Headphones],[/macbook|laptop|notebook/i,Laptop],[/iphone|phone|pixel/i,Smartphone],[/ipad|tablet/i,Tablet],[/watch/i,Watch],[/tv|monitor|display/i,Tv],[/fridge|refrigerator/i,Refrigerator],[/camera|lens/i,Camera],[/milk|yogurt|cream/i,Milk],[/pill|tablet|capsule|medicine/i,Pill],[/shoe|sneaker|nike|adidas|boot/i,Footprints],[/shirt|jacket|dress|coat|pants/i,Shirt]];
const endLabel:Record<Space,string>={expiry:'Expires',warranty:'Warranty ends',return:'Return by',proof:'Valid until'};
const endKey=(s:Space):EndKey=>s==='warranty'?'warranty_end_date':s==='return'?'return_end_date':'expiration_date';
// Sheets portal into the phone screen so they stay inside the device frame on desktop.
const PortalHost=createContext<HTMLElement|null>(null);

async function request(body?:unknown){const res=await fetch('/api/later',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data:any=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Something went wrong. Please try again.');return data;}
function locate():{view:View;id:string}{const p=location.pathname;if(p.startsWith('/item/'))return{view:'item',id:decodeURIComponent(p.split('/')[2]||'')};const view:View=p==='/search'?'search':p==='/storage'?'storage':p==='/add'?'add':'today';return{view,id:''};}
const glyphFor=(item:Pick<Item,'name'|'workspace'|'brand'>)=>item.brand==='Later Note'?MessageSquareText:nameGlyphs.find(([re])=>re.test(item.name))?.[1]??spaceGlyphs[item.workspace];
const kindName=(item:Pick<Item,'workspace'|'brand'>)=>item.brand==='Later Note'?'Note':spaceInfo[item.workspace].name;
const dayNum=(s:string)=>Date.parse(s+'T00:00:00Z')/864e5;
const span=(n:number)=>`${n} day${n===1?'':'s'}`;
const dateText=(s:string|null|undefined)=>s?new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'';
const fileKind=(mime?:string)=>mime?.startsWith('image/')?'Photo':mime==='application/pdf'?'PDF':'Document';
const sampleImage=(item:Pick<Item,'name'|'demo'>)=>!item.demo?'':/macbook|laptop/i.test(item.name)?'/sample-macbook.jpg':/milk/i.test(item.name)?'/sample-milk.jpg':/shoe|nike|sneaker/i.test(item.name)?'/sample-shoes.jpg':'';
async function passwordHash(value:string){const bytes=new TextEncoder().encode(`later-local:${value}`);const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');}
async function avatarData(file:File){if(file.size>5*1024*1024)throw new Error('Choose an image under 5 MB');const url=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const next=new Image();next.onload=()=>resolve(next);next.onerror=()=>reject(new Error('Could not read that photo'));next.src=url;});const size=Math.min(img.naturalWidth,img.naturalHeight),left=(img.naturalWidth-size)/2,top=(img.naturalHeight-size)/2,canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;canvas.getContext('2d')!.drawImage(img,left,top,size,size,0,0,256,256);return canvas.toDataURL('image/jpeg',.82);}finally{URL.revokeObjectURL(url);}}
// The dev runtime rejects request bodies near 1 MB, and a 1600px photo still reads clearly.
async function shrinkImage(file:File){if(!file.type.startsWith('image/')||file.size<=700*1024)return file;const url=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const next=new Image();next.onload=()=>resolve(next);next.onerror=()=>reject(new Error('unreadable'));next.src=url;});const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);let smallest:Blob|null=null;for(const quality of [.85,.7,.55]){const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(!blob)continue;smallest=blob;if(blob.size<=700*1024)break;}return smallest&&smallest.size<file.size?new File([smallest],file.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'}):file;}catch{return file;}finally{URL.revokeObjectURL(url);}}
function countdown(item:Item,now:string){const d=daysLeft(item,now),s=item.workspace,isNote=item.brand==='Later Note';
 if(d===null)return{num:'',unit:s==='proof'?'Stored':'No date yet'};
 if(d<0)return{num:span(-d),unit:isNote?'since your reminder':s==='warranty'?'past warranty':s==='return'?'past the return window':'past its date'};
 if(d===0)return{num:'Today',unit:isNote?'your reminder is due':s==='warranty'?'warranty ends':s==='return'?'last day to return':'it expires'};
 return{num:span(d),unit:isNote?'until your reminder':s==='warranty'?'until warranty ends':s==='return'?'left to return':'until it expires'};}
function elapsed(item:Item,now:string){const end=deadline(item),start=item.purchase_date;if(!end||!start||end<=start)return null;return Math.min(1,Math.max(0,(dayNum(now)-dayNum(start))/(dayNum(end)-dayNum(start))));}

function Shot({item,mime,className=''}:{item:Item;mime?:string;className?:string}){const [broken,setBroken]=useState(false),sample=sampleImage(item),src=mime?.startsWith('image/')?`/api/evidence/${item.evidence_id}`:sample;return <span className={'shot '+className} data-space={item.workspace}>{src&&!broken?<img src={src} alt="" loading="lazy" onError={()=>setBroken(true)}/>:createElement(glyphFor(item),{strokeWidth:1.3})}</span>;}
function Feature({item,mime,now,note,index,onOpen}:{item:Item;mime?:string;now:string;note?:string;index:number;onOpen:()=>void}){const c=countdown(item,now),d=daysLeft(item,now);return <button className="feature" style={{'--i':index} as CSSProperties} onClick={onOpen}><Shot item={item} mime={mime} className="cover"/><span className="feature-body"><span className="feature-text"><span className="name">{item.name}</span><span className={'days'+(d!==null&&d<0?' over':'')}>{c.num||c.unit}</span>{c.num&&<span className="until">{c.unit}</span>}{note&&<span className="whisper">{note}</span>}</span><ChevronRight className="chev" size={20}/></span></button>;}
function Mini({item,mime,now,index,onOpen}:{item:Item;mime?:string;now:string;index:number;onOpen:()=>void}){const c=countdown(item,now),d=daysLeft(item,now);return <button className="mini" style={{'--i':index} as CSSProperties} onClick={onOpen}><Shot item={item} mime={mime} className="cover"/><span className="mini-body"><span className="mini-text"><span className="name">{item.name}</span><span className={'days sm'+(d!==null&&d<0?' over':'')}>{c.num||c.unit}</span></span><ChevronRight className="chev" size={16}/></span></button>;}
function Row({item,mime,now,index,onOpen}:{item:Item;mime?:string;now:string;index:number;onOpen:()=>void}){const end=deadline(item);return <button className="row-card" style={{'--i':index} as CSSProperties} onClick={onOpen}><Shot item={item} mime={mime} className="tile"/><span className="row-text"><strong>{item.name}</strong><span className="sub">{end?dateText(end):countdown(item,now).unit}</span></span><span className="tag">{kindName(item)}</span><ChevronRight className="chev" size={18}/></button>;}
function Sheet({open,onClose,title,action,className='',children}:{open:boolean;onClose:()=>void;title:string;action?:ReactNode;className?:string;children:ReactNode}){const host=useContext(PortalHost);return <V.Root open={open} onOpenChange={o=>{if(!o)onClose();}}><V.Portal container={host??undefined}><V.Overlay className="sheet-overlay"/><V.Content className={'sheet '+className}><div className="sheet-handle" aria-hidden="true"/><div className="sheet-head"><V.Title className="sheet-title">{title}</V.Title>{action}</div><V.Description className="sr-only">{title}</V.Description><div className="sheet-body">{children}</div></V.Content></V.Portal></V.Root>;}
function DateRow({label,value,onChange,flag=false}:{label:string;value:string|null;onChange:(v:string|null)=>void;flag?:boolean}){return <div className="row date-row"><span>{label}{flag&&<i className="flag" title="Please check"/>}</span><span className={'val'+(value?'':' placeholder')}>{value?dateText(value):'Not set'}</span>{value&&<button type="button" className="clear" aria-label={`Clear ${label}`} onClick={()=>onChange(null)}><X size={13}/></button>}<input type="date" value={value||''} aria-label={label} onChange={e=>onChange(e.target.value||null)} onClick={e=>{try{e.currentTarget.showPicker();}catch{/* native picker opens on tap */}}}/></div>;}
function ItemForm({value,onChange}:{value:ItemInput;onChange:(x:ItemInput)=>void}){const key=endKey(value.workspace),unsure=(f:string)=>value.uncertain_fields.includes(f);
 // Switching space carries a recognised deadline over instead of silently dropping it.
 function pick(s:Space){const from=endKey(value.workspace),to=endKey(s);onChange({...value,workspace:s,...(from!==to&&value[from]&&!value[to]?{[to]:value[from],[from]:null}:{})});}
 return <div className="form"><input className="name-input" value={value.name} maxLength={120} autoComplete="off" placeholder="Name" aria-label="Name" onChange={e=>onChange({...value,name:e.target.value})}/><div className="seg" role="radiogroup" aria-label="Kind">{spaces.map(s=><button type="button" role="radio" aria-checked={value.workspace===s} key={s} className={value.workspace===s?'on':''} onClick={()=>pick(s)}>{spaceInfo[s].name}</button>)}</div><div className="group"><DateRow label={value.workspace==='proof'?'Signed':'Bought'} value={value.purchase_date} flag={unsure('purchase_date')} onChange={v=>onChange({...value,purchase_date:v})}/><DateRow label={endLabel[value.workspace]} value={value[key]} flag={unsure(key)} onChange={v=>onChange({...value,[key]:v})}/><label className="row note-row"><span>Note</span><textarea rows={Math.min(4,Math.max(1,Math.ceil(value.notes.length/26)))} value={value.notes} maxLength={3000} placeholder="Optional" onChange={e=>onChange({...value,notes:e.target.value})}/></label></div>{!value[key]&&value.workspace!=='proof'&&<p className="hint">No date found. You can add it later.</p>}</div>;}
function AuthGate({onDone}:{onDone:(p:Profile)=>void}){const [mode,setMode]=useState<'welcome'|'signin'|'register'>('welcome'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[working,setWorking]=useState(false),[hasAccount,setHasAccount]=useState(false);
 useEffect(()=>{try{setHasAccount(Boolean(localStorage.getItem(ACCOUNT_KEY)));}catch{/* private mode */}},[]);
 async function submit(kind:'signin'|'register'){setMessage('');if(!email.includes('@')){setMessage('Enter a valid email address.');return;}if(password.length<6){setMessage('Use at least 6 characters for your password.');return;}if(kind==='register'&&!name.trim()){setMessage('Tell us what to call you.');return;}setWorking(true);try{const hash=await passwordHash(password);if(kind==='register'){const profile={name:name.trim(),email:email.trim().toLowerCase()},account:Account={...profile,passwordHash:hash};localStorage.setItem(ACCOUNT_KEY,JSON.stringify(account));localStorage.setItem(SESSION_KEY,'1');localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));localStorage.removeItem(SAMPLES_KEY);onDone(profile);}else{const raw=localStorage.getItem(ACCOUNT_KEY);if(!raw)throw new Error('No account is saved on this device yet.');const account=JSON.parse(raw) as Account;if(account.email.toLowerCase()!==email.trim().toLowerCase()||account.passwordHash!==hash)throw new Error('Email or password does not match.');const profile:Profile={name:account.name,email:account.email,avatar:account.avatar};localStorage.setItem(SESSION_KEY,'1');localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));onDone(profile);}}catch(e){setMessage((e as Error).message);}finally{setWorking(false);}}
 if(mode==='welcome')return <div className="screen auth auth-welcome"><div className="auth-art"><span className="auth-orbit"><Sparkles size={24}/></span><p className="wordmark">Later</p><p className="script lead">Not now.<br/>But someday.</p></div><div className="auth-copy"><h1>Save now.<br/>Remember later.</h1></div><div className="auth-actions"><button className="btn block" onClick={()=>setMode('register')}>Create an account <ArrowRight size={18}/></button><button className="btn block ghost" onClick={()=>setMode('signin')}>{hasAccount?'Sign in':'I already have an account'}</button><p className="fine">All data will stay on your device.</p></div></div>;
 return <div className="screen auth auth-form"><button className="auth-back" aria-label="Back" onClick={()=>{setMode('welcome');setMessage('');}}><ChevronLeft size={22}/></button><p className="wordmark">Later</p><div className="auth-heading"><h1>{mode==='register'?'Create your account':'Sign in to Later'}</h1></div><form onSubmit={e=>{e.preventDefault();void submit(mode);}}>{mode==='register'&&<label className="auth-field"><UserRound size={18}/><input autoFocus value={name} maxLength={40} autoComplete="name" placeholder="Your name" onChange={e=>setName(e.target.value)}/></label>}<label className="auth-field"><Mail size={18}/><input autoFocus={mode==='signin'} value={email} maxLength={120} type="email" autoComplete="email" placeholder="Email address" onChange={e=>setEmail(e.target.value)}/></label><label className="auth-field"><LockKeyhole size={18}/><input value={password} minLength={6} maxLength={128} type="password" autoComplete={mode==='register'?'new-password':'current-password'} placeholder="Password" onChange={e=>setPassword(e.target.value)}/></label>{message&&<p className="auth-error">{message}</p>}<button className="btn block" disabled={working} type="submit">{working?<LoaderCircle className="spin" size={18}/>:mode==='register'?'Create account':'Sign in'}</button></form><button className="auth-switch" onClick={()=>{setMode(mode==='register'?'signin':'register');setMessage('');}}>{mode==='register'?'Already have an account? Sign in':'New to Later? Create an account'}</button></div>;}

export default function LaterApp({initialView='today',initialId=''}:{initialView?:View;initialId?:string}){
const [view,setView]=useState<View>(initialView),[selectedId,setSelectedId]=useState(initialId),[lastTab,setLastTab]=useState<Tab>(initialView==='search'?'search':'today');
const [data,setData]=useState<Snapshot>({items:[],alerts:[],today:today(),pilotdeck:null,evidence:{}}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('');
const [profile,setProfile]=useState<Profile|null>(null),[profileDraft,setProfileDraft]=useState<Profile|null>(null),[ready,setReady]=useState(false),[profileOpen,setProfileOpen]=useState(false),[profileEditOpen,setProfileEditOpen]=useState(false);
const [showSamples,setShowSamples]=useState(false);
const [query,setQuery]=useState(''),[storageQuery,setStorageQuery]=useState('');
const [uploadFile,setUploadFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[uploading,setUploading]=useState(false),[uploadStep,setUploadStep]=useState(''),[draft,setDraft]=useState<ItemInput|null>(null),[draftEvidence,setDraftEvidence]=useState(''),[uploadWarning,setUploadWarning]=useState('');
const [viewer,setViewer]=useState<{id:string;mime:string}|null>(null),[edit,setEdit]=useState<ItemInput|null>(null),[noteOpen,setNoteOpen]=useState(false),[note,setNote]=useState('');
const [quickNoteOpen,setQuickNoteOpen]=useState(false),[quickNoteTitle,setQuickNoteTitle]=useState(''),[quickNoteText,setQuickNoteText]=useState(''),[quickNoteDate,setQuickNoteDate]=useState(addDays(today(),1));
const [host,setHost]=useState<HTMLElement|null>(null);
const fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),avatarRef=useRef<HTMLInputElement>(null),scrollRef=useRef<HTMLDivElement>(null),previewRef=useRef(''),scanned=useRef(false);
function setUpload(file:File|null){if(previewRef.current)URL.revokeObjectURL(previewRef.current);previewRef.current=file?URL.createObjectURL(file):'';setUploadFile(file);setPreview(previewRef.current);}
async function reload(){try{const result=await request();setData({evidence:{},...result});setError('');return result as Snapshot;}catch(e){setError((e as Error).message);return null;}finally{setLoading(false);}}
useEffect(()=>{try{const raw=localStorage.getItem(PROFILE_KEY),account=localStorage.getItem(ACCOUNT_KEY),session=localStorage.getItem(SESSION_KEY);setShowSamples(localStorage.getItem(SAMPLES_KEY)==='1');if(raw&&(!account||session==='1')){setProfile(JSON.parse(raw));if(!account)localStorage.setItem(SESSION_KEY,'1');}}catch{/* first run */}setReady(true);},[]);
useEffect(()=>{void (async()=>{const snap=await reload();
 // One quiet scan per session keeps deadlines fresh without a manual button.
 if(snap&&!scanned.current&&snap.items.some(i=>i.status==='active')){scanned.current=true;try{await request({action:'scan'});await reload();}catch{/* alerts stay as stored */}}})();
 const interval=setInterval(()=>void reload(),60000);const sync=()=>{const at=locate();setView(at.view);if(at.id)setSelectedId(at.id);if(at.view==='today'||at.view==='search')setLastTab(at.view);};sync();window.addEventListener('popstate',sync);return()=>{clearInterval(interval);window.removeEventListener('popstate',sync);};},[]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'later_list_items',title:'List Later items',description:'Read saved belongings and active alerts. Does not change data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw new Error('No arguments accepted');const result=await request();setData({evidence:{},...result});return{items:result.items.map((i:Item)=>({id:i.id,name:i.name,workspace:i.workspace,status:i.status,deadline:deadline(i)})),alerts:result.alerts.filter((a:Alert)=>a.status==='active')};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);

function saveProfile(p:Profile){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(p));const raw=localStorage.getItem(ACCOUNT_KEY);if(raw)localStorage.setItem(ACCOUNT_KEY,JSON.stringify({...JSON.parse(raw),...p}));setShowSamples(localStorage.getItem(SAMPLES_KEY)==='1');}catch{/* private mode */}setProfile(p);}
function signOut(){try{localStorage.removeItem(SESSION_KEY);}catch{/* private mode */}setProfileOpen(false);setShowSamples(false);setProfile(null);go('today');}
async function chooseAvatar(file:File){try{const avatar=await avatarData(file);setProfileDraft(current=>current?{...current,avatar}:current);}catch(e){toast.error((e as Error).message);}finally{if(avatarRef.current)avatarRef.current.value='';}}
function go(next:View,id?:string){setView(next);if(id)setSelectedId(id);if(next==='today'||next==='search')setLastTab(next);history.pushState(null,'',next==='item'?`/item/${id}`:paths[next]);scrollRef.current?.scrollTo(0,0);window.scrollTo(0,0);}
async function action(label:string,body:unknown){setBusy(label);try{const r=await request(body);await reload();return r;}catch(e){toast.error((e as Error).message);return null;}finally{setBusy('');}}
async function saveQuickNote(){const r=await action('note',{action:'note',title:quickNoteTitle,text:quickNoteText,remind_on:quickNoteDate});if(r?.item){setQuickNoteOpen(false);setQuickNoteTitle('');setQuickNoteText('');setQuickNoteDate(addDays(data.today,1));toast.success('Reminder saved');go('item',r.item.id);void action('scan',{action:'scan'});}}
function resetAdd(){setDraft(null);setDraftEvidence('');setUpload(null);setUploadWarning('');}
async function upload(file:File){if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)){toast.error('Choose an image or PDF');return;}if(file.size>(file.type==='application/pdf'?8:25)*1024*1024){toast.error(file.type==='application/pdf'?'PDFs must be under 8 MB':'Photos must be under 25 MB');return;}resetAdd();setUpload(file);setUploading(true);setUploadStep('');go('add');try{const form=new FormData();form.set('file',await shrinkImage(file));if(file.type==='application/pdf'){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer(),isEvalSupported:false}).promise;if(pdf.numPages>6){await pdf.destroy();throw new Error('PDFs can have up to 6 pages');}for(let p=1;p<=pdf.numPages;p++){setUploadStep(`Page ${p} of ${pdf.numPages}`);const page=await pdf.getPage(p),vp=page.getViewport({scale:1});const viewport=page.getViewport({scale:Math.min(1.8,1500/Math.max(vp.width,vp.height))});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvas,canvasContext:canvas.getContext('2d')!,viewport}).promise;const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not read that file')),'image/jpeg',.85));form.append('pages',blob,`page-${p}.jpg`);canvas.width=0;canvas.height=0;}await pdf.destroy();setUploadStep('');}const r=await fetch('/api/upload',{method:'POST',body:form});const result:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||`Upload failed (${r.status}). Please try again.`);setDraft({...empty,...result.recognition});setDraftEvidence(result.evidence_id);setUploadWarning(result.warning?'Could not read it. Please fill in the details.':'');}catch(e){setUploadWarning((e as Error).message);toast.error((e as Error).message);}finally{setUploading(false);if(fileRef.current)fileRef.current.value='';if(cameraRef.current)cameraRef.current.value='';}}
async function confirm(){if(!draft)return;const r=await action('confirm',{action:'confirm',item:draft,evidence_id:draftEvidence});if(r?.item){toast.success('Saved');resetAdd();go('item',r.item.id);void action('scan',{action:'scan'});}}

const now=data.today;
const visibleItems=data.items.filter(i=>showSamples||!i.demo);
const activeItems=visibleItems.filter(i=>i.status==='active');
const activeAlerts=data.alerts.filter(a=>a.status==='active'&&activeItems.some(i=>i.id===a.item_id));
const alertFor=(id:string)=>activeAlerts.find(a=>a.item_id===id);
// Alerts first (soonest first), then upcoming deadlines, then items without one.
const rank=(i:Item)=>{const d=daysLeft(i,now),alert=alertFor(i.id);return (alert?.memory_context?-1e6:alert?0:d===null?2e6:1e6)+(d??0);};
const sorted=[...activeItems].sort((a,b)=>rank(a)-rank(b));
const close=sorted.filter(i=>alertFor(i.id)).length;
const selected=data.items.find(i=>i.id===selectedId),selectedAlert=selected?alertFor(selected.id):undefined;
const match=(i:Item,q:string)=>(i.name+' '+i.notes+' '+(i.brand||'')+' '+spaceInfo[i.workspace].name).toLowerCase().includes(q);
const results=query.trim()?sorted.concat(visibleItems.filter(i=>i.status==='archived')).filter(i=>match(i,query.trim().toLowerCase())):[];
const stored=sorted.concat(visibleItems.filter(i=>i.status==='archived')).filter(i=>!storageQuery.trim()||match(i,storageQuery.trim().toLowerCase()));
const mime=(i:Item)=>data.evidence[i.evidence_id];
const open=(i:Item)=>go('item',i.id);
const letter=(profile?.name||'L').trim().charAt(0).toUpperCase();
const banner=error?<button className="banner" onClick={()=>void reload()}>Connection hiccup. Tap to retry.</button>:null;
const skeleton=<div className="list">{[0,1].map(i=><div className="skeleton" key={i}/>)}</div>;
const avatarStyle=profile?.avatar?{backgroundImage:`url(${profile.avatar})`}:undefined;
const head=<header className="head"><h1 className="wordmark">Later</h1><button className={'avatar'+(profile?.avatar?' photo':'')} style={avatarStyle} onClick={()=>setProfileOpen(true)} aria-label="Profile">{profile?.avatar?'':letter}</button></header>;

if(!ready)return <div className="stage"><div className="device"><div className="glass"><div className="app"><div className="splash"><p className="wordmark">Later</p></div></div></div></div></div>;
if(!profile)return <div className="stage"><div className="device"><div className="glass"><div className="app bare"><AuthGate onDone={saveProfile}/></div></div></div></div>;

return <PortalHost.Provider value={host}><div className="stage">
<div className="stage-brand" aria-hidden="true"><p className="wordmark">Later</p><p className="script">Not now.<br/>But someday.</p><p className="stage-line">Keep the paper.<br/>Remember the date.</p></div>
<div className="device"><div className="glass" ref={setHost}><div className={'app'+(view==='add'||view==='item'?' bare':'')+(view==='today'?' bg-today':view==='search'?' bg-search':'')} ref={scrollRef}><Toaster position="top-center" toastOptions={{className:'toast'}}/>
<main>
{view==='today'&&<section className="screen today-screen" key="today">{head}
{(loading||close>0||activeItems.length>0)&&<p className="head-sub">{loading?'Loading…':close?`${close} thing${close===1?'':'s'} ${close===1?'is':'are'} getting close.`:'Nothing needs you today.'}</p>}{banner}
{loading?skeleton:sorted.length?<>
 <Feature item={sorted[0]} mime={mime(sorted[0])} now={now} index={0} note={alertFor(sorted[0].id)?.recommendation} onOpen={()=>open(sorted[0])}/>
 {sorted.length>1&&<div className="mini-grid">{sorted.slice(1,3).map((i,n)=><Mini key={i.id} item={i} mime={mime(i)} now={now} index={n+1} onOpen={()=>open(i)}/>)}</div>}
 {sorted.length>3&&<button className="more" onClick={()=>go('storage')}>All {sorted.length} items<ChevronRight size={16}/></button>}
 <p className="script center">A calmer tomorrow.</p></>
:<div className="empty"><span className="blob sm"><Plus size={28} strokeWidth={1.6}/></span><h2>Nothing saved yet</h2><button className="btn" onClick={()=>go('add')}>Add something</button></div>}</section>}

{view==='search'&&<section className="screen search-screen" key="search">{head}
{!query&&<><span className="blob"><Search size={42} strokeWidth={1.5}/></span><h2 className="ask">What are you<br/>looking for?</h2></>}
<div className={'searchbox'+(query?' up':'')}><Search size={18} className="chev"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find something in Later..." aria-label="Search" autoComplete="off"/>{query&&<button className="clear" aria-label="Clear" onClick={()=>setQuery('')}><X size={14}/></button>}</div>
{query?results.length?<div className="list">{results.map((i,n)=><Row key={i.id} item={i} mime={mime(i)} now={now} index={n} onOpen={()=>open(i)}/>)}</div>:<p className="quiet">Nothing found.</p>
:<p className="script bottom">Save today for a brighter tomorrow.</p>}</section>}

{view==='storage'&&<section className="screen" key="storage"><div className="topnav"><button className="icon-btn" aria-label="Back" onClick={()=>go(lastTab)}><ChevronLeft size={26}/></button><span/><button className={'avatar sm'+(profile.avatar?' photo':'')} style={avatarStyle} onClick={()=>setProfileOpen(true)} aria-label="Profile">{profile.avatar?'':letter}</button></div>
<h1 className="page-title">My Storage</h1>
<div className="searchbox"><Search size={18} className="chev"/><input value={storageQuery} onChange={e=>setStorageQuery(e.target.value)} placeholder="Search storage..." aria-label="Search storage" autoComplete="off"/>{storageQuery&&<button className="clear" aria-label="Clear" onClick={()=>setStorageQuery('')}><X size={14}/></button>}</div>
{loading?skeleton:stored.length?<div className="list">{stored.map((i,n)=><Row key={i.id} item={i} mime={mime(i)} now={now} index={n} onOpen={()=>open(i)}/>)}</div>:<p className="quiet">{storageQuery?'Nothing found.':'Nothing stored yet.'}</p>}</section>}

{view==='item'&&<section className="screen" key={'item-'+selectedId}><div className="topnav"><button className="icon-btn" aria-label="Back" onClick={()=>history.length>1?history.back():go(lastTab)}><ChevronLeft size={26}/></button><span/>{selected&&<button className="icon-btn" aria-label="Edit" onClick={()=>setEdit({...selected})}><Pencil size={19}/></button>}</div>
{selected?(()=>{const c=countdown(selected,now),end=deadline(selected),pct=elapsed(selected,now),d=daysLeft(selected,now);return <>
<Shot item={selected} mime={mime(selected)} className="cover hero"/>
<h1 className="item-name">{selected.name}</h1>
<span className="pill">{kindName(selected)}{selected.demo?' · Sample':''}{selected.status==='archived'?' · Archived':''}</span>
<div className={'count'+(d!==null&&d<0?' over':'')}><span className={'days xl'+(d!==null&&d<0?' over':'')}>{c.num||c.unit}</span>{c.num&&<span className="until">{c.unit}</span>}{pct!==null?<div className="span"><div className="bar"><i style={{width:`${Math.max(pct*100,3)}%`}}/></div><div className="span-dates"><span>{dateText(selected.purchase_date)}</span><span>{dateText(end)}</span></div></div>:end&&<span className="until">{dateText(end)}</span>}</div>
{selectedAlert&&<div className="read"><span className="read-label"><Sparkles size={14}/>Later&apos;s read</span><p>{selectedAlert.recommendation}</p><button disabled={!!busy} onClick={async()=>{if(await action('resolve',{action:'resolve',id:selectedAlert.id}))toast.success('Marked done');}}><Check size={16}/>Mark done</button></div>}
<div className="group">{selected.purchase_date&&pct===null&&<div className="row"><span>{selected.workspace==='proof'?'Signed':'Bought'}</span><span className="val">{dateText(selected.purchase_date)}</span></div>}{selected.brand&&<div className="row"><span>Brand</span><span className="val">{selected.brand}</span></div>}{selected.notes&&<div className="row multi"><span>Note</span><span className="val">{selected.notes}</span></div>}</div>
<div className="section-head"><span>Evidence</span></div>
<button className="evidence" onClick={()=>setViewer({id:selected.evidence_id,mime:mime(selected)||''})}><Shot item={selected} mime={mime(selected)} className="tile"/><span className="row-text"><strong>Original file</strong><span className="sub">{fileKind(mime(selected))}</span></span><ExternalLink size={17} className="chev"/></button>
{selected.evidence_quote&&<p className="quote">{selected.evidence_quote}</p>}
<div className="section-head"><span>Notes</span><button onClick={()=>setNoteOpen(true)}><Plus size={16}/>Add</button></div>
<div className="timeline">{[...selected.memory].sort((a,b)=>b.date.localeCompare(a.date)).map(m=><div className={'tl'+(m.source==='user'?' mine':'')} key={m.id}><time>{dateText(m.date)}</time><p>{m.text.replace(/\.$/,'')}</p></div>)}</div>
<button className="archive" disabled={!!busy} onClick={async()=>{const r=await action('archive',{action:'archive',id:selected.id});if(r)toast.success(selected.status==='active'?'Archived':'Restored');}}>{selected.status==='active'?'Archive':'Restore'}</button></>;})()
:<div className="empty"><span className="blob sm"><FileText size={26} strokeWidth={1.5}/></span><p>{loading?'Loading…':'That item is gone.'}</p></div>}</section>}

{view==='add'&&<section className="screen" key="add"><div className="topnav"><button className="icon-btn" aria-label="Close" onClick={()=>{resetAdd();go(lastTab);}}><X size={22}/></button><span className="topnav-title">{draft&&!uploading?'Check the details':''}</span><span/></div>
{uploading?<div className="scan"><div className="scan-frame">{preview&&uploadFile?.type.startsWith('image/')?<img src={preview} alt=""/>:<FileText size={48} strokeWidth={1.2}/>}</div><h2>Reading it</h2>{uploadStep&&<p>{uploadStep}</p>}</div>
:draft?<>{uploadWarning&&<p className="warn">{uploadWarning}</p>}<button className="preview" aria-label="View evidence" onClick={()=>setViewer({id:draftEvidence,mime:uploadFile?.type||''})}>{preview&&uploadFile?.type.startsWith('image/')?<img src={preview} alt=""/>:<span className="preview-file"><FileText size={30} strokeWidth={1.4}/>{uploadFile?.name}</span>}</button><ItemForm value={draft} onChange={setDraft}/><div className="bottom-bar"><button className="btn block" disabled={!!busy||!draft.name.trim()} onClick={()=>void confirm()}>{busy==='confirm'&&<LoaderCircle className="spin" size={18}/>}Save</button></div></>
:<div className="start"><div className="add-visual"><span className="add-camera"><Camera size={36} strokeWidth={1.35}/></span><p className="script">One snap.<br/>A little less to remember.</p></div><h2>Save the evidence</h2>{uploadWarning&&<p className="warn">{uploadWarning}</p>}<div className="add-actions"><button className="btn block" onClick={()=>cameraRef.current?.click()}><Images size={19}/>Photo library</button><button className="btn block ghost" onClick={()=>fileRef.current?.click()}><Images size={19}/>Document</button><button className="btn block ghost" onClick={()=>setQuickNoteOpen(true)}><MessageSquareText size={19}/>Note</button></div></div>}</section>}
</main>

{view!=='add'&&view!=='item'&&<nav className="tabbar" aria-label="Main">
 <button className={'tab'+(view==='today'?' on':'')} onClick={()=>go('today')} aria-current={view==='today'?'page':undefined}><CalendarDays strokeWidth={view==='today'?2.1:1.7}/>Today</button>
 <button className="fab" aria-label="Add" onClick={()=>go('add')}><Plus strokeWidth={2.2}/></button>
 <button className={'tab'+(view==='search'?' on':'')} onClick={()=>go('search')} aria-current={view==='search'?'page':undefined}><Search strokeWidth={view==='search'?2.1:1.7}/>Search</button></nav>}
<input className="sr-only" ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,application/pdf" aria-label="Choose a document" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><input className="sr-only" ref={cameraRef} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Photo library" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><input className="sr-only" ref={avatarRef} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Choose profile photo" onChange={e=>{const f=e.target.files?.[0];if(f)void chooseAvatar(f);}}/>
</div></div></div>

<Sheet open={profileOpen} onClose={()=>setProfileOpen(false)} title="Profile" action={<button className="sheet-action" onClick={()=>{setProfileDraft({...profile});setProfileOpen(false);setProfileEditOpen(true);}}>Edit</button>}><div className="profile"><span className={'avatar lg'+(profile.avatar?' photo':'')} style={avatarStyle} aria-hidden="true">{profile.avatar?'':letter}</span><strong>{profile.name}</strong>{profile.email&&<span>{profile.email}</span>}</div><div className="group"><button className="row" onClick={()=>{setProfileOpen(false);go('storage');}}><span>My Storage</span><ChevronRight className="chev" size={18}/></button><button className="row danger-row" onClick={signOut}><span>Sign out</span><LogOut size={17}/></button></div></Sheet>
<Sheet open={profileEditOpen} onClose={()=>{setProfileEditOpen(false);setProfileDraft(null);}} title="Edit profile">{profileDraft&&<><div className="profile-editor"><button className={'avatar lg editable'+(profileDraft.avatar?' photo':'')} style={profileDraft.avatar?{backgroundImage:`url(${profileDraft.avatar})`}:undefined} onClick={()=>avatarRef.current?.click()} aria-label="Change profile photo">{profileDraft.avatar?'':profileDraft.name.trim().charAt(0).toUpperCase()||'L'}<span><Camera size={14}/></span></button><button className="photo-link" onClick={()=>avatarRef.current?.click()}>Change photo</button></div><label className="profile-field"><span>Name</span><input value={profileDraft.name} maxLength={40} autoComplete="name" onChange={e=>setProfileDraft({...profileDraft,name:e.target.value})}/></label><label className="profile-field"><span>Email</span><input value={profileDraft.email} maxLength={120} type="email" autoComplete="email" onChange={e=>setProfileDraft({...profileDraft,email:e.target.value})}/></label><button className="btn block mt" disabled={!profileDraft.name.trim()||!profileDraft.email.includes('@')} onClick={()=>{saveProfile({...profileDraft,name:profileDraft.name.trim(),email:profileDraft.email.trim()});setProfileEditOpen(false);setProfileDraft(null);toast.success('Profile updated');}}>Save changes</button></>}</Sheet>
<Sheet open={quickNoteOpen} onClose={()=>setQuickNoteOpen(false)} title="Add a note"><div className="quick-note"><span className="quick-note-icon"><CalendarClock size={25}/></span><label><span>Title</span><input value={quickNoteTitle} maxLength={120} autoFocus placeholder="e.g. Renew home insurance" onChange={e=>setQuickNoteTitle(e.target.value)}/></label><label><span>Remind me</span><input type="date" min={data.today} value={quickNoteDate} onChange={e=>setQuickNoteDate(e.target.value)}/></label><label><span>Note</span><textarea rows={4} maxLength={1500} value={quickNoteText} placeholder="Add the detail you will need later…" onChange={e=>setQuickNoteText(e.target.value)}/></label><button className="btn block mt" disabled={!!busy||!quickNoteTitle.trim()||!quickNoteText.trim()||!quickNoteDate} onClick={()=>void saveQuickNote()}>{busy==='note'?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>}Save reminder</button></div></Sheet>
<Sheet open={!!viewer} onClose={()=>setViewer(null)} title="Evidence" className="viewer" action={viewer&&<a className="icon-btn" href={`/api/evidence/${viewer.id}`} target="_blank" rel="noreferrer" aria-label="Open in a new tab"><ExternalLink size={18}/></a>}>{viewer&&(viewer.mime.startsWith('image/')?<img className="viewer-media" src={`/api/evidence/${viewer.id}`} alt="Original evidence"/>:<iframe className="viewer-media" title="Original evidence" src={`/api/evidence/${viewer.id}`}/>)}</Sheet>
<Sheet open={!!edit} onClose={()=>setEdit(null)} title="Edit">{edit&&<><ItemForm value={edit} onChange={setEdit}/><button className="btn block mt" disabled={!!busy||!edit.name.trim()} onClick={async()=>{if(!selected)return;const r=await action('update',{action:'update',id:selected.id,item:edit});if(r){setEdit(null);toast.success('Updated');void action('scan',{action:'scan'});}}}>Save</button></>}</Sheet>
<Sheet open={noteOpen} onClose={()=>setNoteOpen(false)} title="Add a note"><textarea className="note-input" rows={4} maxLength={1500} value={note} onChange={e=>setNote(e.target.value)} placeholder="e.g. Charging drops out" aria-label="Note"/><button className="btn block mt" disabled={!!busy||!note.trim()} onClick={async()=>{if(!selected)return;const r=await action('issue',{action:'issue',id:selected.id,text:note});if(r){setNote('');setNoteOpen(false);toast.success('Noted');void action('scan',{action:'scan'});}}}>Save</button></Sheet>
</div></PortalHost.Provider>;
}
