import {createServer} from 'node:http';
import {readFileSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {resolve,basename} from 'node:path';
import {randomUUID,timingSafeEqual} from 'node:crypto';
import {FileMemoryStore} from '../.pilotdeck-source/src/context/memory/edgeclaw-memory-core/src/core/file-memory.ts';
import {CronScheduler} from '../.pilotdeck-source/src/cron/runtime/CronScheduler.ts';
import {CronTaskStore} from '../.pilotdeck-source/src/cron/storage/CronTaskStore.ts';
import {computeNextRunAt} from '../.pilotdeck-source/src/cron/runtime/CronSchedule.ts';
import {resolveCronPaths} from '../.pilotdeck-source/src/cron/storage/CronPaths.ts';
import type {CronTask} from '../.pilotdeck-source/src/cron/protocol/types.ts';
const root=resolve('.later');mkdirSync(root,{recursive:true});
const config=Object.fromEntries(readFileSync('.dev.vars','utf8').split('\n').filter(x=>x.includes('=')).map(x=>[x.slice(0,x.indexOf('=')),x.slice(x.indexOf('=')+1)]));
const secret=config.LATER_BRIDGE_TOKEN;if(!secret)throw new Error('LATER_BRIDGE_TOKEN required');
const spaces=['expiry','warranty','return','proof'];
const stores=new Map(spaces.map(space=>{const workspace=resolve(root,'workspaces',space);mkdirSync(workspace,{recursive:true});const store=new FileMemoryStore(resolve(workspace,'.pilotdeck','memory'),{manageUserProfile:false});store.upsertProjectMeta({projectName:`Later / ${space}`,description:`Later ${space} confirmed facts and original evidence`,status:'in_progress'});return[space,store];}));
const taskStore=new CronTaskStore(resolveCronPaths({pilotHome:root,projectKey:resolve(root,'workspaces')}));
let active=0,lastScan:any=null;
const schedule={type:'cron' as const,expression:'0 9 * * *',timezone:'Asia/Shanghai'};
async function runTask(task:CronTask,runId:string){if(active)return;active++;const startedAt=new Date().toISOString();await taskStore.updateTask(task.taskId,t=>({...t,status:'running',lastRunId:runId}));try{const response=await fetch('http://localhost:4173/api/cron',{method:'POST',headers:{Authorization:`Bearer ${config.LATER_SCAN_TOKEN}`},signal:AbortSignal.timeout(180000)});if(!response.ok)throw new Error('Later scan unavailable');lastScan={at:new Date().toISOString(),...(await response.json() as any)};await taskStore.appendRun({schemaVersion:1,taskId:task.taskId,runId,sessionKey:'later-monitor',startedAt,finishedAt:new Date().toISOString(),outcome:'completed'});}catch{lastScan={at:new Date().toISOString(),error:'检查未完成，将在服务恢复后重试。'};await taskStore.appendRun({schemaVersion:1,taskId:task.taskId,runId,sessionKey:'later-monitor',startedAt,finishedAt:new Date().toISOString(),outcome:'failed'});}finally{await taskStore.updateTask(task.taskId,t=>({...t,status:'scheduled',nextRunAt:lastScan?.error?new Date(Date.now()+60000).toISOString():computeNextRunAt(schedule,new Date())!.toISOString(),updatedAt:new Date().toISOString(),revision:(t.revision||0)+1}));active--;}}
const current=await taskStore.getTask('later-daily');if(!current)await taskStore.putTask({schemaVersion:1,taskId:'later-daily',message:'Inspect active Later items, read memory, evaluate deadline risk and bind alerts to original evidence.',schedule,status:'scheduled',sessionKey:'later-monitor',channelKey:'later',projectKey:resolve(root,'workspaces'),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),nextRunAt:computeNextRunAt(schedule,new Date())!.toISOString(),scheduleComputationVersion:2});else if(current.status==='running')await taskStore.updateTask(current.taskId,t=>({...t,status:'scheduled'}));
const scheduler=new CronScheduler({config:{enabled:true,timezone:'Asia/Shanghai',maxConcurrentRuns:1,runTimeoutMinutes:3},store:taskStore,fire:{runTask} as any,uuid:randomUUID,now:()=>new Date(),activeRunCount:()=>active,logger:{warn:m=>console.warn(m)}});await scheduler.start();
function authorized(token:string){const a=Buffer.from(token),b=Buffer.from(`Bearer ${secret}`);return a.length===b.length&&timingSafeEqual(a,b);}
const server=createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');if(!authorized(req.headers.authorization||'')){res.writeHead(401);res.end('{"error":"Unauthorized"}');return;}try{if(req.url==='/status'){const task=await taskStore.getTask('later-daily');res.end(JSON.stringify({connected:true,engine:'PilotDeck FileMemoryStore + CronScheduler',next_run:task?.nextRunAt,last_scan:lastScan,workspaces:spaces.map(s=>({name:s,memories:stores.get(s)!.countMemoryEntries()}))}));return;}let body='';for await(const part of req){body+=part;if(body.length>14*1024*1024)throw new Error('Payload too large');}const data=JSON.parse(body||'{}');if(req.url==='/memory'){const item=data.item;if(!spaces.includes(item?.workspace)||!/^[-a-zA-Z0-9]+$/.test(item.id))throw new Error('Invalid item');const bodyText=['# '+item.name,'Item ID: '+item.id,'Workspace: '+item.workspace,'Status: '+item.status,'Evidence ID: '+item.evidence_id,'',JSON.stringify({purchase_date:item.purchase_date,expiration_date:item.expiration_date,warranty_end_date:item.warranty_end_date,return_end_date:item.return_end_date}),'',...(item.memory||[]).map((m:any)=>`${m.date} [${m.source}]: ${m.text}`)].join('\n');const store=stores.get(item.workspace)!;const record=store.upsertCandidate({type:'project',scope:'project',name:item.id,description:item.name,body:bodyText,sourceSessionKey:'later-'+item.id,capturedAt:item.created_at});if(data.file){const dir=resolve(root,'workspaces',item.workspace,'files',item.id);mkdirSync(dir,{recursive:true});writeFileSync(resolve(dir,basename(data.file.name)),Buffer.from(data.file.base64,'base64'));}res.end(JSON.stringify({ok:true,memory_file:record.relativePath}));return;}if(req.url==='/recall'){if(!spaces.includes(data.workspace))throw new Error('Invalid workspace');const store=stores.get(data.workspace)!;const entries=store.listMemoryEntries({query:data.item_id});const records=store.getMemoryRecordsByIds(entries.map(e=>e.relativePath));res.end(JSON.stringify({text:records.map(r=>r.content).join('\n'),count:records.length}));return;}res.writeHead(404);res.end('{"error":"Not found"}');}catch{res.writeHead(400);res.end('{"error":"PilotDeck operation failed"}');}});
server.listen(4174,'127.0.0.1',()=>console.log('Later PilotDeck bridge: http://127.0.0.1:4174 (authenticated)'));
// Catch up missed inspections on startup without making page visits responsible for scheduling.
setTimeout(()=>void runTask({...current,taskId:'later-daily'} as CronTask,randomUUID()),15000);
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{void scheduler.stop().then(()=>server.close(()=>process.exit(0)));});
